heat_template_version: 2014-10-16

description: A template to deploy a load balanced web server

resources:
  server_nodes:
      type: OS::Heat::ResourceGroup
      properties:
      #A completer
        count: 2
        resource_def:
          type: OS::Nova::Server
          properties:
              name: Server_%index%
              image: INF4410-Ubuntu-trusty-mini
              flavor: INF4410-mini
              user_data_format: RAW
              networks: [{ "network": inf4410-net}]
              user_data: |
                      #!/bin/bash
                      wget https://raw.githubusercontent.com/houssemmh/INF4410-TP3/master/server.py
                      python server.py &

  mypool:
      type: OS::Neutron::Pool
      #A completer
      properties:
          protocol: HTTP
          monitors: [{get_resource: mymonitor}]
          subnet: inf4410-subnet
          lb_method: ROUND_ROBIN
          vip:
            protocol_port: 8080

  myloadbalancer:
      type: OS::Neutron::LoadBalancer
      #A completer
      properties:
        members: { get_attr: [server_nodes, refs] }
        protocol_port: 8080
        pool_id: {get_resource: mypool}

  mymonitor:
      type: OS::Neutron::HealthMonitor
      properties:
        type: HTTP
        delay: 15
        max_retries: 1
        timeout: 5	

  lb_floating:
    type: OS::Neutron::FloatingIP
    properties:
      floating_network: ext-net
      port_id: {get_attr: [mypool, vip, port_id]}


outputs:
  pool_ip_address:
    value: {get_attr: [mypool, vip, address]}
    description: The IP address of the load balancing pool