heat_template_version: 2013-05-23

description: >
  Server HOT template that just defines a single server.

parameters:
  key_name:
    type: string
    description: Name of an existing key pair to use for the server
    default: bineta-demba
  flavor:
    type: string
    description: Flavor for the server to be created
    default: INF4410-mini
  image:
    type: string
    description: Image ID or image name to use for the server
    default: INF4410-Ubuntu-trusty-mini
  admin_pass:
    type: string
    description: Admin password
    default: Adminbd
    hidden: true
    constraints:
      - length: { min: 6, max: 8 }
        description: Password length must be between 6 and 8 characters
      - allowed_pattern: "[a-zA-Z0-9]+"
        description: Password must consist of characters and numbers only
      - allowed_pattern: "[A-Z]+[a-zA-Z0-9]*"
        description: Password must start with an uppercase character
  network:
    type: string
    description: Network name to attach instance to.
    default: inf4410-net
  
  db_port:
    type: number
    description: Database port number
    default: 8080
    constraints:
      - range: { min: 8000, max: 9000 }
        description: Port number must be between 1000 and 9999

resources:
  server:
    type: OS::Nova::Server
    properties:
      key_name: { get_param: key_name }
      flavor: { get_param: flavor }
      image: { get_param: image }
      admin_pass: { get_param: admin_pass }
      user_data_format: RAW
      networks:
        - network: { get_param: network }
      user_data:
        str_replace:
          template: |
            #!/bin/bash
            wget https://raw.githubusercontent.com/houssemmh/INF4410-TP3/master/server.py
            python server.py
          params: 
            db_port: { get_param: db_port }

outputs:
  server_networks:
    description: The networks of the deployed server
    value: { get_attr: [server, networks] }